name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet test
        run: dotnet test --configuration Release
    
      - name: dotnet publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifacts/

  # deploy_dev:
  #   name: Deploy Dev
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: my-artifact
  #         path: artifacts/

  #     - name: 'Deply it to Azure App Service'
  #       uses: azure/webapps-deploy@v2
  #       with: 
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app service name
  #         package:  artifacts/