name: Secrets Workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  API_CSPROJ_PATH: "./scr/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  build:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"
